language: node_js
node_js:
  - '8'

cache: yarn

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

jobs:
  include:
    - stage: npm package
      if: tag IS present
      node_js: '8'
      script: yarn compile
      before_deploy:
        - cd dist/ngx-advanced-pipes
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          tags: true
